# Permalinks
permalink:        /:title/
relative_permalinks: true

# Setup
title:            Josh Buchea
tagline:          Web & Mobile Developer
url:              http://joshbuchea.com
paginate:         5
baseurl:          http://joshbuchea.com/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

#About/contact
author:
  name:           Josh Buchea
  url:            https://twitter.com/joshbuchea
  email:          hello@joshbuchea.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/joshbuchea/site-joshbuchea.com
